version: '3'

networks:
  frontend:
    external:
      name: swarm-net
  backend:

services:
  dpgraham:
    image: nginx
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
    environment:
      - NGINX_HOST=dpgraham.com
      - NGINX_PORT=80
    networks:
      - frontend
      - backend
