kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: dpgraham 
  namespace: dpgraham
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dpgraham
                port:
                  number: 80
