kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: dpgraham
  namespace: dpgraham
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: le-issuer
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - dpgraham.com
    secretName: le-prod
  rules:
    - host: dpgraham.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dpgraham
                port:
                  number: 80
#########################
# Without TLS
# kind: Ingress
# apiVersion: networking.k8s.io/v1
# metadata:
#   name: dpgraham-http
#   namespace: dpgraham
#   annotations:
#     traefik.ingress.kubernetes.io/router.entrypoints: web

# spec:
#   rules:
#     - http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: dpgraham
#                 port:
#                   number: 80
#
###
# HTTP as a traefik IngressRoute instead of k8 Ingress
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: dpgraham-http-ingressroute
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Path(`/`)
    services:
    - kind: Service
      name: dpgraham
      port: 80
    middlewares:
    - name: redirecthttp

