apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: le-issuer
spec:
  acme:
      # Production server
    server: https://acme-v02.api.letsencrypt.org/directory 
      # staging server
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: dpgraham4401@gmail.com
    privateKeySecretRef:
      name: le-prod
    solvers:
    - http01:
        ingress: 
          class: traefik
